chore: added types for element styles
coral-xyz/backpack pull request #1409
Opened 2022-11-02 18:28 UTC by anoushk1234

2022-11-02 18:34 UTC, hkirat requested changes

2022-11-02 18:34 UTC, hkirat commented on packages/react-xnft/package.json
> +    "@coral-xyz/common-public": "^0.2.0-latest.379",
Could you revert this

2022-11-02 18:34 UTC, hkirat commented on yarn.lock
> +"@coral-xyz/common-public@^0.2.0-latest.379":
Could you revert this?

2022-11-02 18:51 UTC, anoushk1234 commented on yarn.lock
> +"@coral-xyz/common-public@^0.2.0-latest.379":
sure, although it wasn't allow me to build without these

2022-11-02 18:59 UTC, anoushk1234 commented
@hkirat is this gtg?

2022-11-02 20:29 UTC, hkirat requested changes

2022-11-02 20:29 UTC, hkirat commented on packages/react-xnft/package.json
> -    "@coral-xyz/common-public": "*",
I think you ended up deleting these by mistake? Can you add those back

2022-11-02 20:29 UTC, hkirat commented on yarn.lock
> +"@coral-xyz/common-public@^0.2.0-latest.379":
I still see  the yarn changes, could you revert to the current lock file?

2022-11-03 14:38 UTC, hkirat commented on packages/react-xnft/src/reconciler.ts
> +type _HostConfig = HostConfig<
I think this flowed over from a merge conflict, mind removing this as well? It's dead code

2022-11-03 15:29 UTC, anoushk1234 commented on packages/react-xnft/src/reconciler.ts
> +type _HostConfig = HostConfig<
yea i think this is from your recent pr, i synced this before pushing and fixed the conflicts as well, ill remove it

2022-11-03 15:59 UTC, merged