Anoushk1234/fix types
coral-xyz/backpack pull request #1426
Opened 2022-11-05 08:38 UTC by anoushk1234

2022-11-05 17:23 UTC, hkirat requested changes
Thanks for the changes @anoushk1234 
Have you tried testing this locally? I remember seeing a reconciler error if we don't set `children` on props to `undefined` because the renderer wouldn't understand `ReactNode` elements
Could you confirm that a few examples compile correctly with this implementation.

2022-11-05 17:23 UTC, hkirat commented on packages/react-xnft/src/reconciler.ts
> +} from "react";
Any reason for these imports? Are they being used somewhere?

2022-11-06 04:34 UTC, anoushk1234 commented on packages/react-xnft/src/elements.tsx
> +  element: NodeProps | (NodeProps & DOMAttributes<NodeProps>)
> We may want to avoid using `DomAttributes` at all since the props would be re-used on native mobile (which doesn't have a concept of DOM)

How is mobile implemented then? Do you have react native attributes? If so i can add those

2022-11-06 15:36 UTC, hkirat commented on packages/react-xnft/src/elements.tsx
> +  element: NodeProps | (NodeProps & DOMAttributes<NodeProps>)
So the idea is for the attributes to be the same on mobile and web since developers are expected to maintain a single codebase. 
For now i think `NodeProps` encapsulates enough of what we can support on both mobile and web.

2022-11-06 16:25 UTC, hkirat commented
<img width="1684" alt="Screenshot 2022-11-06 at 9 52 16 PM" src="https://user-images.githubusercontent.com/8079861/200182272-1a8f6f46-dbd0-499f-ac1d-712eab599551.png">
Compiled this locally on the `prices` example and getting this error. I think this is related to us not overriding `children` to undefined and them being `ReactNode` elements vs our custom `NodeElements`.

2022-11-07 03:58 UTC, anoushk1234 commented on packages/react-xnft/src/elements.tsx
> +  element: NodeProps | (NodeProps & DOMAttributes<NodeProps>)
@hkirat there's also a problem with Nodeprops where it's type only shows as any because the one of the types in it is any

2022-11-07 03:59 UTC, hkirat commented on packages/react-xnft/src/elements.tsx
> +  element: NodeProps | (NodeProps & DOMAttributes<NodeProps>)
Could you elaborate on `one of the types is any` ? Do you mean the because of the `custom` component?

2022-11-07 04:00 UTC, anoushk1234 commented
> <img alt="Screenshot 2022-11-06 at 9 52 16 PM" width="1684" src="https://user-images.githubusercontent.com/8079861/200182272-1a8f6f46-dbd0-499f-ac1d-712eab599551.png">
> Compiled this locally on the `prices` example and getting this error. I think this is related to us not overriding `children` to undefined and them being `ReactNode` elements vs our custom `NodeElements`.

I couldnt find any type called NodeElements

2022-11-07 10:01 UTC, anoushk1234 commented
> <img alt="Screenshot 2022-11-06 at 9 52 16 PM" width="1684" src="https://user-images.githubusercontent.com/8079861/200182272-1a8f6f46-dbd0-499f-ac1d-712eab599551.png">
> Compiled this locally on the `prices` example and getting this error. I think this is related to us not overriding `children` to undefined and them being `ReactNode` elements vs our custom `NodeElements`.

Let me look into this, i couldn't find NodeElements but I'll try to find a workaround

2022-11-07 13:45 UTC, anoushk1234 commented on packages/react-xnft/src/elements.tsx
> +  element: NodeProps | (NodeProps & DOMAttributes<NodeProps>)
@hkirat yes because of CustomProps the entire NodeProps is considered as any which defeats the purpose

2022-11-08 09:56 UTC, hkirat approved these changes
Just the one comment

2022-11-08 09:56 UTC, hkirat commented on packages/react-xnft/src/reconciler.ts
> +    props: TextProps,
The arguments to this fn seems to have changed, but the fn call is the same.
Also raw text shouldn't have any props associated with it, so feel free to just remove this prop.

2022-11-08 11:07 UTC, anoushk1234 commented on packages/react-xnft/src/reconciler.ts
> +    props: TextProps,
I will do that but shouldn't text have the ability to be styled?

2022-11-08 11:13 UTC, hkirat requested changes

2022-11-08 13:01 UTC, anoushk1234 commented
> Did a sweep of all the examples to ensure they're all compiling Added a few more props here - [hkirat@079658f](https://github.com/hkirat/backpack/commit/079658f4864dbf6355bc7e5554d01c34b7572602) Hopefully should be the last of it can you merge these in ^

done and also compiles without issues!

2022-11-09 01:12 UTC, merged

2022-11-09 01:12 UTC, hkirat commented
Thankyou for chugging through this @anoushk1234 !