implemented the rest of the Solana Connection interface methods.
coral-xyz/backpack pull request #1537
Opened 2022-11-18 07:18 UTC by jokumusic

2022-11-19 18:28 UTC, armaniferrante commented on packages/background/src/backend/solana-connection.ts
> -  ///////////////////////////////////////////////////////////////////////////////
Note that this is only partially implemented and won't work as is. You still need to implement the `/frontend/` handlers and the connection client in `/packages/common/`

2022-11-19 20:30 UTC, jokumusic commented on packages/background/src/backend/solana-connection.ts
> -  ///////////////////////////////////////////////////////////////////////////////
I purposely didn't do the frontend implementation because I wasn't sure if there was a design decision to not expose some methods. For instance, you might not want the subscribe methods exposed which could cause extra load on your RPC servers when people don't tear them down when not in use.

2022-11-19 21:02 UTC, jokumusic commented on packages/background/src/backend/solana-connection.ts
> -  ///////////////////////////////////////////////////////////////////////////////
If you give the word, I'll go ahead and expose all the methods to the front end :)

2022-11-19 23:40 UTC, armaniferrante commented on packages/background/src/backend/solana-connection.ts
> -  ///////////////////////////////////////////////////////////////////////////////
Let's do everything except for subscriptions and anything requiring websockets.

2022-11-21 18:12 UTC, armaniferrante commented on packages/background/src/frontend/solana-connection.ts
> +const messageHandlers: Map<string, Function> = new Map();
This is nice but it introduces an inconsistency not found in any of the other APIs. Personally I would recommend removing this but also will let others chime in.

2022-11-21 18:25 UTC, jokumusic commented on packages/background/src/frontend/solana-connection.ts
> +const messageHandlers: Map<string, Function> = new Map();
I noticed a few of the frontend methods were passing what looks like the wrong parameter index, but maybe I'm misunderstanding something. For example, look at getLatestBlockhash() in frontend/solana-connection.ts and solana/background-connection.ts in common:
![image](https://user-images.githubusercontent.com/450089/203131434-d44a5ff2-d0f9-4db6-8b6b-23b1eed33d5a.png)

Shouldn't the frontend call look like ctx.backend.getLatestBlockhashAndContext(params[0]) instead?

2022-11-21 18:27 UTC, armaniferrante commented on packages/background/src/frontend/solana-connection.ts
> +const messageHandlers: Map<string, Function> = new Map();
yes that sounds right

2022-11-22 04:39 UTC, jokumusic commented on packages/background/src/frontend/solana-connection.ts
> +const messageHandlers: Map<string, Function> = new Map();
I've done the grunt work. I don't have any tests that cover all of the methods. Is there a test somewhere that covered the previously existing methods? With most of the methods, I just passed the channel message params straight through to the ackend connection because I didn't know if any serialization/deserialization or something else was needed. Let me know if there's more that I need to do.

2022-12-11 12:25 UTC, hkirat requested changes

2022-12-11 12:25 UTC, hkirat commented on packages/background/src/frontend/solana-connection.ts
> +async function handleSendTransaction(
could u remove the comment ehre

2022-12-11 12:25 UTC, hkirat commented on packages/background/src/frontend/solana-connection.ts
> +async function handleSimulateTransaction(
can u remove the commend here?

2022-12-11 18:05 UTC, jokumusic commented on packages/background/src/frontend/solana-connection.ts
> +async function handleSendTransaction(
I commented it out because the arguments to the function aren't primitive types and probably need to be deserialized. I'm not really sure how to go about that right now.

2022-12-11 18:05 UTC, jokumusic commented on packages/background/src/frontend/solana-connection.ts
> +async function handleSimulateTransaction(
I commented it out because the arguments to the function aren't primitive types and probably need to be deserialized. I'm not really sure how to go about that right now.

2022-12-11 18:22 UTC, jokumusic commented on packages/background/src/frontend/solana-connection.ts
> +async function handleSendTransaction(
Also, the Signer type contains public/private key, so I don't think the signature of the function is correct. It should probably just be the pubkey managed by the wallet and then the wallet will confirm the signature.

2022-12-11 18:22 UTC, jokumusic commented on packages/background/src/frontend/solana-connection.ts
> +async function handleSimulateTransaction(
Also, the Signer type contains public/private key, so I don't think the signature of the function is correct. It should probably just be the pubkey managed by the wallet and then the wallet will confirm the signature.

2022-12-13 12:49 UTC, hkirat approved these changes

2022-12-13 14:39 UTC, merged