fixes media, reply, mentions and minor ui bugs
coral-xyz/backpack pull request #2392
Opened 2023-02-01 18:45 UTC by irffanasiff

2023-02-01 19:52 UTC, hkirat requested changes

2023-02-01 19:52 UTC, hkirat commented on packages/chat-sdk/src/components/MediaContent.tsx
> +  console.log("background - ", theme.custom.colors.background);
remove log

2023-02-01 19:52 UTC, hkirat commented on packages/chat-sdk/src/components/MediaContent.tsx
> +                  maxHeight: !isXs ? 260 : 180,
Could you explain this logic a little (why heights use px and width uses `vw` ?

2023-02-01 19:52 UTC, hkirat commented on packages/chat-sdk/src/components/messageInput/MessageInput.tsx
> +            {offlineMembers
Is `offlineMembers` defined now?
Might be an issue with the merge conflict. Check the build for more details

2023-02-02 04:03 UTC, irffanasiff commented on packages/chat-sdk/src/components/MediaContent.tsx
> +                  maxHeight: !isXs ? 260 : 180,
the height is fixed for media but it can go to any width but not larger than screen-size

2023-02-02 04:41 UTC, closed without merging