autofocus message input
coral-xyz/backpack pull request #3066
Opened 2023-03-01 14:37 UTC by yash-w3

Yooo new heree, I am a Open source dev. Created web3 gh account for now. 

**Changes**

1. Autofocus the message input, added the flag to prevent autofocus in case its needed
2. Fixed lint issues & minor refactor

Fixes: #3032

2023-03-01 15:55 UTC, hkirat requested changes

2023-03-01 15:55 UTC, hkirat commented on packages/chat-sdk/src/components/messageInput/MessageInput.tsx
> +      const messageElement = document.getElementById(messageInputElementId);
Can you use a ref here instead of `document.getElementById` ?

2023-03-01 17:14 UTC, yash-w3 commented on packages/chat-sdk/src/components/messageInput/MessageInput.tsx
> +      const messageElement = document.getElementById(messageInputElementId);
No, actually we can't use it here, if you see the library code they are not using `forwardRef` to pass `ref` to the underlying element. I did give it a try but turned out I was getting `undefined` since its ref to function component which returns undefined or null based on default value you pass

2023-03-01 18:04 UTC, hkirat approved these changes

2023-03-01 19:09 UTC, merged

2023-03-03 16:16 UTC, hkirat commented on packages/chat-sdk/src/components/messageInput/MessageInput.tsx
> +      const messageElement = document.getElementById(messageInputElementId);
Note- For now merged it in but might be good to clean it up later on