bug resolved:on changing email field button should be reset to notify me
coral-xyz/backpack pull request #3471
Opened 2023-03-29 12:06 UTC by mohitgadhavi1

issue no : #3470 . it was a small bug  which resolve those issue where asking for email

2023-03-29 12:17 UTC, mohitgadhavi1 commented
I accidentally push to master branch (:

2023-03-31 00:44 UTC, hkirat requested changes

2023-03-31 00:44 UTC, hkirat commented on yarn.lock
> -  resolution: "eslint-plugin-zeus-custom@file:./eslint-plugin-zeus-custom#./eslint-plugin-zeus-custom::hash=a463b5&locator=eslint-config-custom%40workspace%3Apackages%2Feslint-config-custom"
Can u revert this?

2023-03-31 05:20 UTC, mohitgadhavi1 commented on yarn.lock
> -  resolution: "eslint-plugin-zeus-custom@file:./eslint-plugin-zeus-custom#./eslint-plugin-zeus-custom::hash=a463b5&locator=eslint-config-custom%40workspace%3Apackages%2Feslint-config-custom"
sure. this change has been committed.

2023-04-01 13:21 UTC, hkirat commented on yarn.lock
> +  checksum: 4e0331830d706a4ca5ab1743380087993e015437310bf5565a0fd885d8476bd2e5af942d3401bdc8c506b1536281f4358c1c9a17512ebb365bf359cfdb6180a6
still seeing a change here

2023-04-02 12:47 UTC, mohitgadhavi1 commented on yarn.lock
> +  checksum: 4e0331830d706a4ca5ab1743380087993e015437310bf5565a0fd885d8476bd2e5af942d3401bdc8c506b1536281f4358c1c9a17512ebb365bf359cfdb6180a6
ok. I have reverted this change also.

2023-04-03 11:42 UTC, mohitgadhavi1 commented on yarn.lock
> +  checksum: 4e0331830d706a4ca5ab1743380087993e015437310bf5565a0fd885d8476bd2e5af942d3401bdc8c506b1536281f4358c1c9a17512ebb365bf359cfdb6180a6
I shouldnt have included this file in first place.

2023-04-03 12:44 UTC, hkirat commented on yarn.lock
> +  checksum: 4e0331830d706a4ca5ab1743380087993e015437310bf5565a0fd885d8476bd2e5af942d3401bdc8c506b1536281f4358c1c9a17512ebb365bf359cfdb6180a6
Look at the number of changes
![Uploading Screenshot 2023-04-03 at 6.14.30 PM.jpg…]()

2023-04-03 12:51 UTC, closed without merging