enhancement: don't allow wallet names to start with '@' #3202
coral-xyz/backpack pull request #3513
Opened 2023-03-31 01:25 UTC by jeivardan

resolves [#3202](https://github.com/coral-xyz/backpack/issues/3202) in both create and rename wallet

<img width="374" alt="renameWallet" src="https://user-images.githubusercontent.com/36626247/228999578-6c2f94b0-cf6a-4666-9463-bc356aecb923.png">

<img width="369" alt="createWallet" src="https://user-images.githubusercontent.com/36626247/228999608-68d1775f-f07b-4693-95a0-dde00037e9be.png">

2023-03-31 19:16 UTC, hkirat requested changes

2023-03-31 19:16 UTC, hkirat commented on packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/RenameWallet.tsx
> +    if (!regExp.test(walletName)) {
Seems like code is duplicated in two files. Can u move it to either common or some place inside `app-extension`?
Other than that looks good

2023-04-01 02:11 UTC, jeivardan commented on packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/RenameWallet.tsx
> +    if (!regExp.test(walletName)) {
Sure will look into it and will make the changes

2023-04-01 04:37 UTC, jeivardan commented on packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/RenameWallet.tsx
> +    if (!regExp.test(walletName)) {
@hkirat I moved the code to common

2023-04-01 05:02 UTC, jeivardan reviewed
@hkirat I moved the code to common

2023-04-10 05:16 UTC, jeivardan commented on packages/common/src/utils.ts
> +  let regExp = new RegExp("^(?!@.*$).*");
Yep it is too generic and I've made the changes

2023-04-10 05:17 UTC, jeivardan commented on packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/RenameWallet.tsx
> +      setIsPrimaryDisabled(walletName.trim() === "" ? true : false);
Yeah! Simplified it. Thanks for the suggestion.

2023-12-25 09:55 UTC, closed without merging