Incorrect button showing on profile of someone who has sent you a friend request
coral-xyz/backpack pull request #3515
Opened 2023-03-31 12:08 UTC by atulya2109

Fixes: #3505 

- Sets button text to Accept Friend Request after checking if `remoteRequested` is set for userId.

2023-03-31 19:14 UTC, hkirat requested changes

2023-03-31 19:14 UTC, hkirat commented on packages/message-sdk/src/components/ProfileScreen.tsx
> +      const remoteRequested: boolean = await getRemoteRequest(json.user.id);
you shouldn't need to send another request here. 
The request above (`${BACKEND_API_URL}/friends?userId=${userId}`) should return `remoteRequested` if it doesn't already

2023-03-31 20:14 UTC, atulya2109 commented on packages/message-sdk/src/components/ProfileScreen.tsx
> +      const remoteRequested: boolean = await getRemoteRequest(json.user.id);
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/20705464/229220647-dec3c1be-c2bb-4546-97d4-7be6ebb7b8ec.png">

This endpoint doesn't return `remoteRequested`

2023-03-31 20:21 UTC, hkirat commented on packages/message-sdk/src/components/ProfileScreen.tsx
> +      const remoteRequested: boolean = await getRemoteRequest(json.user.id);
Can you add `remoteRequested` to the endpoing? You should be able to find the logic/code in the `backend` module

2023-03-31 20:23 UTC, atulya2109 commented on packages/message-sdk/src/components/ProfileScreen.tsx
> +      const remoteRequested: boolean = await getRemoteRequest(json.user.id);
Sure, will do.

2023-03-31 20:27 UTC, hkirat commented on packages/message-sdk/src/components/ProfileScreen.tsx
> +      const remoteRequested: boolean = await getRemoteRequest(json.user.id);
Awesome!

2023-03-31 21:59 UTC, atulya2109 commented on packages/message-sdk/src/components/ProfileScreen.tsx
> +      const remoteRequested: boolean = await getRemoteRequest(json.user.id);
Quick question, how do i run the `backend` module locally?

2023-03-31 22:23 UTC, hkirat commented on packages/message-sdk/src/components/ProfileScreen.tsx
> +      const remoteRequested: boolean = await getRemoteRequest(json.user.id);
cd `backend/native/backpack-api` 
yarn start

Then change the URL here to http://localhost:8080 - https://github.com/coral-xyz/backpack/blob/master/packages/common/src/constants.ts#L583

2023-04-01 09:42 UTC, atulya2109 commented on packages/message-sdk/src/components/ProfileScreen.tsx
> +      const remoteRequested: boolean = await getRemoteRequest(json.user.id);
Got it. Sorry to bother you again, but I'm getting this error when running `backpack-api` locally.

![image](https://user-images.githubusercontent.com/20705464/229278435-999748aa-6569-4e5a-b18a-0f6b0a1791a8.png)

2023-04-01 11:15 UTC, hkirat commented on packages/message-sdk/src/components/ProfileScreen.tsx
> +      const remoteRequested: boolean = await getRemoteRequest(json.user.id);
Can you do the following as well - 
```
cd backend/reef
docker-compose up
```

to run the database locally

2023-04-01 19:27 UTC, atulya2109 commented on packages/message-sdk/src/components/ProfileScreen.tsx
> +      const remoteRequested: boolean = await getRemoteRequest(json.user.id);
Ok, thanks.

2023-04-19 14:02 UTC, atulya2109 commented
Hi @hkirat, just a gentle reminder to review the requested changes.

2023-12-25 09:55 UTC, closed without merging