updated color of link for accepting friend request
coral-xyz/backpack pull request #3602
Opened 2023-04-04 21:13 UTC by Anubhav311

This PR updates the color of the `Accept` link button for friend request notifications. 

A new `acceptFriendRequest` color is created as a global variable for reusability and convention. 

I have not changed the `blue` color as it is being used by some other components also.

https://github.com/coral-xyz/backpack/issues/3594

2023-04-20 19:29 UTC, Anubhav311 commented
As per the updated info, I've changed the global variable `blue` instead of creating a new variable.
Can you please have a look @callensm

2023-04-26 07:23 UTC, hkirat requested changes

2023-04-26 07:23 UTC, hkirat commented on packages/themes/src/colors.ts
> +  blue: "#4C94FF",
Hi can you confirm this isn't being used other places?
Since this'll update everywhere `theme.custom.colors.blue` is being used

2023-04-26 07:23 UTC, hkirat commented on packages/themes/src/colors.ts
> +  blue: "#0057EB",
same comment as above

2023-12-25 09:55 UTC, closed without merging