Yatharth1706/profile enhancements
coral-xyz/backpack pull request #3753
Opened 2023-04-21 10:47 UTC by yatharth1706

This PR fixes the issue https://github.com/coral-xyz/backpack/issues/3572

Have completed and made all the designs which are there in the issue description. 

Attaching some final screenshots after complete fix in the code for reference. 

![ProfileScreen2](https://user-images.githubusercontent.com/32243289/233617190-fb93eaba-894d-477a-ab85-a905bf13bbea.jpg)
![ProfileScreen1](https://user-images.githubusercontent.com/32243289/233617199-71f3e6e1-568a-4642-ae6f-a0b3a15f1484.jpg)
![FriendsList1](https://user-images.githubusercontent.com/32243289/233617202-f4f30526-d8ec-4c68-81d7-a4b36060ce55.jpg)

2023-04-25 17:52 UTC, hkirat requested changes

2023-04-25 17:52 UTC, hkirat commented on packages/app-extension/src/components/Unlocked/Messages/MessageOptions.tsx
> +  console.log("props");
remove

2023-04-25 17:52 UTC, hkirat commented on packages/app-extension/src/components/common/Layout/Router.tsx
> +  console.log(props); // TODO: fix type
remove

2023-04-25 17:52 UTC, hkirat commented on packages/message-sdk/src/components/FriendsScreen.tsx
> +  const allChatsOfOtherUser = useContacts(userId);
useContacts doesn't return the friends of the other user. Can u confirm you're getting the right value here?
You most probably need to expose a new endpoint that'll give u the friends count of the other user

2023-04-25 18:56 UTC, aarongillett commented
Thanks for reviewing this @hkirat ! 
Visually the avatars also need to: 
- match the size and padding of the [mockup](https://github.com/coral-xyz/backpack/issues/3572)
- have a border around the avatars

2023-04-26 05:58 UTC, yatharth1706 commented on packages/app-extension/src/components/Unlocked/Messages/MessageOptions.tsx
> +  console.log("props");
ok

2023-04-26 06:01 UTC, yatharth1706 commented on packages/message-sdk/src/components/FriendsScreen.tsx
> +  const allChatsOfOtherUser = useContacts(userId);
I confirmed, I was getting friends list using this as this hook accepts the userId of the user. Can you confirm from your end. Because while doing testing, I confirmed, it was giving me correct friends list. 

Only thing that i noticed with the useContacts hook was that even if friend request is accepted, it doesn't show in the friends list until unless some message exchange as happened with the friend.  

Other than its working fine and it shows correct friend list

2023-04-26 06:03 UTC, yatharth1706 commented
> Thanks for reviewing this @hkirat ! Visually the avatars also need to:
> 
> * match the size and padding of the [mockup](https://github.com/coral-xyz/backpack/issues/3572)
> * have a border around the avatars

Will try to match it according to the mockup.

2023-04-28 22:46 UTC, aarongillett commented
@hkirat / @yatharth1706 what else is needed to merge this PR?

2023-04-29 03:55 UTC, yatharth1706 commented on packages/app-extension/src/components/Unlocked/Messages/MessageOptions.tsx
> +  console.log("props");
done

2023-04-29 03:56 UTC, yatharth1706 commented on packages/app-extension/src/components/common/Layout/Router.tsx
> +  console.log(props); // TODO: fix type
done

2023-04-29 03:56 UTC, yatharth1706 commented on packages/message-sdk/src/components/FriendsScreen.tsx
> +  const allChatsOfOtherUser = useContacts(userId);
once confirm about it as useContacts giving correct friends list but its logic is little different i guess

2023-04-29 03:57 UTC, yatharth1706 commented
> @hkirat / @yatharth1706 what else is needed to merge this PR?

hi @aarongillett, i have made changes which @hkirat suggested, except the last one useContacts one. Have asked him to confirm this once as this hook gives correct friends list. 

All changes have been done from my side

2023-12-25 09:55 UTC, closed without merging